// Generated by CoffeeScript 1.10.0

/* Define Controller */

(function() {
  var streamUIController;

  streamUIController = function($scope, $http) {
    var vm;
    vm = this;
    vm.icons = ['../assets/svg/account.svg', '../assets/svg/hangouts.svg', '../assets/svg/menu.svg'];
    vm.streams = [];
    $http.get('streams.json').then(function(streams) {
      vm.streams = streams.data;
    });
  };

  angular.module('streamUIApp').controller('streamUIController', ['$scope', '$http', streamUIController]);

}).call(this);
