// Generated by CoffeeScript 1.10.0
(function() {
  var translateController;

  translateController = function($scope, $http) {
    var assignSelection, vm;
    vm = this;
    vm.languages = null;
    vm.selection = 0;
    vm.firstLanguage = 'test';
    vm.mainLanguage = '';
    vm.secondLanguage = '';
    $http.get('data.json').then(function(data) {
      vm.languages = data['data'];
      assignSelection(vm.languages, 0);
    });
    assignSelection = function(languages, selection) {
      if (!_.isEmpty(languages)) {
        vm.mainLanguage = languages[selection]['English'];
        vm.firstLanguage = languages[selection]['French'];
        vm.secondLanguage = languages[selection]['German'];
      }
    };
  };

  angular.module('translateApp').controller('translateController', ['$scope', '$http', translateController]);

}).call(this);

//# sourceMappingURL=controller.js.map
