// Generated by CoffeeScript 1.10.0

/* Controller top - no function hoisting */

(function() {
  var translateController;

  translateController = function($scope, $http) {
    var assignSelection, vm;
    vm = this;
    vm.languages = null;
    vm.selection = 0;
    vm.firstLanguage = 'test';
    vm.mainLanguage = '';
    vm.secondLanguage = '';
    vm.date = _.now();

    /* Get data from json file */
    $http.get('data.json').then(function(data) {
      vm.languages = data['data'];
      assignSelection(vm.languages, vm.selection);
    });

    /* Function to assign languages based on selection */
    assignSelection = function(languages, selection) {
      if (!_.isEmpty(languages)) {
        vm.mainLanguage = languages[selection]['English'];
        vm.firstLanguage = languages[selection]['French'];
        vm.secondLanguage = languages[selection]['German'];
      }
    };

    /* Function to increment selection */
    vm.incrementSelection = function() {
      if (vm.selection >= vm.languages.length - 1) {
        vm.selection = 0;
      } else {
        vm.selection++;
      }
    };

    /* Watch for changes in selection */
    $scope.$watch('vm.selection', function(oldValue, newValue) {
      if (oldValue !== newValue) {
        assignSelection(vm.languages, newValue);
      }
    });
  };

  angular.module('translateApp').controller('translateController', ['$scope', '$http', translateController]);

}).call(this);

//# sourceMappingURL=controller.js.map
